#Test - confirm that PRLs produced are the same

print("Retrieving the PRLs matrix made available in Iorio 2015 paper. This takes 20 sec")
load("../DATA/DRUG_PRLs.ro")
print("Retrieving the matrix with the PRLs produced. This takes 30 sec")
my_DRUG_PRLs=read.table("../OUTPUT/DrugPRLs.txt",check.names = FALSE,stringsAsFactors = FALSE,header=TRUE)
#' samePRL was created to test if the PRL for one drug obtained with my code is the same as the one in DRUG_PRLs, the data table provided by Iorio 2015.
#' 
#' @param drug The drug whose PRL we generated
#' @param DRUG_PRLs Data frame with the PRLs generated by Iorio
#' @return TRUE if the two PRLs are the same, FALSE if not
samePRL=function(drug,DRUG_PRLs){
  my_PRL=generatePRLfromFile(drug)
  drug=gsub(" ", "_", drug)
  if(startsWith(drug,"\"")){
    drug = substring(drug, 2, nchar(drug)-1)
  }
  Iorio_PRL=DRUG_PRLs[,which(colnames(DRUG_PRLs)==drug)]
  return(identical(my_PRL[,1],Iorio_PRL))
}

#Test - This command returns a vector in which is each element is True if the PRL obtained with my code is the same as the one obtained by Iorio 2010 for the drug corresponding to that element
#Takes approximately 10 min.
#drugs = unique(instances$cmap_name)
#samePRLs=sapply(drugs,samePRL,DRUG_PRLs=DRUG_PRLs) # it yields 2 FALSE  (that is due to differences in drug identifiers, not because PRLs are indeed different, as it is shown at the end)

print("Reordering the columns of the PRLs matrix produced so that it can be compared with the matrix made available in Iorio 2015 paper")
#Confirm that I could have obtained the exact same matrix as DRUG_PRLs with my code:
#To confirm I've obtained the exact same matrix, I have to make sure that all drugs have the exact same names
#colnames(DRUG_PRLs)[which(!colnames(DRUG_PRLs)%in%colnames(my_DRUG_PRLs))] #- this yields 2 drugs
colnames(my_DRUG_PRLs)[which(colnames(my_DRUG_PRLs)=="6-bromoindirubin-3'-oxime")]="6-bromoindirubin-3-oxime"
colnames(my_DRUG_PRLs)[which(startsWith(colnames(my_DRUG_PRLs),"HNMPA"))]="HNMPA--AM-3"
my_DRUG_PRLs_ordered=my_DRUG_PRLs[,colnames(DRUG_PRLs)]
attributes(my_DRUG_PRLs_ordered)["row.names"][[1]]=as.integer(rownames(my_DRUG_PRLs_ordered))
print(paste("Matrices have the same content:",identical(my_DRUG_PRLs_ordered,DRUG_PRLs),sep=""))
# Must yield TRUE
